#* Get Weather Key
GET http://localhost:9000/weatherApiKey

###
@url = "http://localhost:9000"

### Create a new User
POST http://localhost:9000/users/signup
Content-Type: application/json

{
    "username": "Eleni 2",
    "email": "eleni@gmails.com",
    "password": "123456789"

}

### User Login 
POST {{url}}/login
Content-Type: application/json

{
    "username": "Test 1",
    "email": "test1@example.org",
    "password": "12345678",
    
}

### Create a new cloth item
POST {{url}}/upload
Content-Type: application/json

{
    "type": 
    
    

}
