#* Get Weather Key
GET http://localhost:8000/weatherApiKey

###
@url = "http://localhost:9000"

### Create a new User
POST {{url}}/signup
Content-Type: application/json

{
    "username": "Test 1",
    "email": "test1@example.org",
    "password": "12345678",

}

### User Login 
POST {{url}}/login
Content-Type: application/json

{
    "username": "Test 1",
    "email": "test1@example.org",
    "password": "12345678",
    
}

### Create a new cloth item
POST {{url}}/upload
Content-Type: application/json

{
    "type": 
    
    

}
